# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: |
          noop || (echo "test=Failed" >> "$GITHUB_OUTPUT" && exit 1)
  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ always() }}
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"

  job3:
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ failure() && needs.job1.outputs.output2 == 'Failed' }}
    steps:
      - name: test
        run: echo test

  job4:
    runs-on: ubuntu-latest
    steps:
      - run: |
          qwqifiiafi
          echo "hello~~"
